name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3, nightly]
        julia-arch: [x86]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
          - os: macOS-latest
            julia-version: nightly
          - os: windows-latest
            julia-version: nightly
    
    steps:
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v0.2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: "Run tests"
        run: |
          julia --project -e "using Pkg; Pkg.instantiate();"
          julia --project -e "using Pkg; Pkg.test();"
